In [5]:
import requests
import json
import pandas as pd

# Fungsi untuk ekstraksi data dari platform e-commerce
def ekstrak_data(url):
    try:
        # Melakukan request ke URL endpoint platform e-commerce
        response = requests.get(url)
        # Mengecek apakah request berhasil (kode status 200)
        if response.status_code == 200:
            # Mengambil data JSON dari response
            data_json = response.json()
            # Mengkonversi data JSON menjadi DataFrame pandas
            data_frame = pd.DataFrame(data_json)
            return data_frame
        else:
            # Jika request gagal, mencetak pesan error
            print("Request gagal dengan kode status:", response.status_code)
            return None
    except Exception as e:
        # Jika terjadi kesalahan lain selama proses ekstraksi, mencetak pesan error
        print("Terjadi kesalahan saat melakukan ekstraksi data:", str(e))
        return None

# URL endpoint platform e-commerce
url_ecommerce = 'https://gist.githubusercontent.com/nadirbslmh/8fc9cc6cd5cbaaf5cbff63b090fb497e/raw/a7bf3e1edab88b04314a40a9de3ed744bc86d0e9/ecommerce.json'
data_transaksi = ekstrak_data(url_ecommerce)


# Tampilkan data transaksi yang berhasil diekstrak
print("Data transaksi yang berhasil diekstrak:")
data_transaksi

Data transaksi yang berhasil diekstrak:

,transaction_id,transaction_date,customer_name,transaction_amount,item_category,item_name,payment_method,status
0,1,01-11-2023,John Doe,50.0,book,The Great Gatsby,credit card,success
1,2,01-11-2023,Jane Smith,120.5,gaming,PlayStation 5,cash,success
2,3,02-11-2023,Bob Johnson,800.0,technology,Laptop,credit card,failed
3,4,03-11-2023,Alice Williams,30.0,kitchen,Coffee Maker,e wallet,success
4,5,03-11-2023,Charlie Brown,150.0,book,To Kill a Mockingbird,credit card,success
...,...,...,...,...,...,...,...,...
95,96,21-12-2023,Oliver Brown,15.0,kitchen,Peeler,credit card,success
96,97,21-12-2023,Chloe Wilson,75.5,book,The Road,credit card,success
97,98,22-12-2023,Ella Harris,30.0,gaming,Board Game: Monopoly,cash,success
98,99,22-12-2023,Liam Turner,180.0,technology,Bluetooth Earbuds,e wallet,success
99,100,23-12-2023,Mia Robinson,10.0,kitchen,Can Opener,credit card,success

In [19]:
# Filter transaksi yang menggunakan metode pembayaran kartu kredit (credit card) dan memiliki status 'success'
transaksi_cc_success = data_transaksi[(data_transaksi['payment_method'] == 'credit card') & (data_transaksi['status'] == 'success')]

# Menampilkan hasil
transaksi_cc_success

,transaction_id,transaction_date,customer_name,transaction_amount,item_category,item_name,payment_method,status
0,1,01-11-2023,John Doe,50.0,book,The Great Gatsby,credit card,success
4,5,03-11-2023,Charlie Brown,150.0,book,To Kill a Mockingbird,credit card,success
8,9,05-11-2023,Olivia Martin,350.0,book,1984,credit card,success
11,12,07-11-2023,William Turner,18.0,kitchen,Toaster,credit card,success
15,16,10-11-2023,Lily Anderson,8.0,kitchen,Kitchen Scale,credit card,success
16,17,10-11-2023,Mason Evans,280.0,book,The Catcher in the Rye,credit card,success
19,20,12-11-2023,Isabella Martinez,35.0,kitchen,Cookware Set,credit card,success
20,21,12-11-2023,Noah Clark,9.0,book,Lord of the Rings Trilogy,credit card,success
24,25,15-11-2023,Ava Jones,17.0,book,The Hobbit,credit card,success
26,27,16-11-2023,Sophie Davis,500.0,technology,Laptop,credit card,success
28,29,17-11-2023,Liam Wilson,300.0,book,Harry Potter Box Set,credit card,success
31,32,19-11-2023,Grace Moore,19.0,kitchen,Toaster Oven,credit card,success
32,33,19-11-2023,Ella Davis,75.0,book,The Shining,credit card,success
36,37,21-11-2023,Aiden Turner,160.0,book,The Da Vinci Code,credit card,success
39,40,23-11-2023,Mia Robinson,8.0,kitchen,Kitchen Timer,credit card,success
40,41,23-11-2023,Noah Wilson,270.0,book,Game of Thrones Box Set,credit card,success
43,44,25-11-2023,Sophia Turner,25.0,kitchen,Knife Set,credit card,success
44,45,25-11-2023,Oliver Hill,30.0,book,The Hunger Games Trilogy,credit card,success
47,48,27-11-2023,Ethan Turner,9.0,kitchen,Baking Sheet,credit card,success
48,49,27-11-2023,Chloe Brown,40.5,book,The Alchemist,credit card,success
51,52,29-11-2023,Lucas Harris,15.0,kitchen,Peeler,credit card,success
52,53,29-11-2023,Amelia Turner,28.5,book,The Girl on the Train,credit card,success
56,57,01-12-2023,Sophie Robinson,80.0,book,The Maze Runner Series,credit card,success
59,60,03-12-2023,Ella Taylor,20.0,kitchen,Mixing Spoon Set,credit card,success
60,61,03-12-2023,Aria Hill,45.0,book,The Fault in Our Stars,credit card,success
63,64,05-12-2023,Mia Harris,15.0,kitchen,Cake Pan,credit card,success
64,65,05-12-2023,Sophia Turner,60.0,book,The Chronicles of Narnia Box Set,credit card,success
67,68,07-12-2023,Chloe Davis,8.0,kitchen,Measuring Cups Set,credit card,success
71,72,09-12-2023,Ava Harris,18.0,kitchen,Kitchen Shears,credit card,success
72,73,09-12-2023,Ella Turner,65.0,book,The Girl with the Dragon Tattoo,credit card,success
76,77,11-12-2023,Aiden Smith,120.0,book,The Outsiders,credit card,success
79,80,13-12-2023,Amelia Robinson,14.0,kitchen,Whisk,credit card,success
80,81,13-12-2023,Liam Taylor,25.5,book,The Art of War,credit card,success
83,84,15-12-2023,Oliver Davis,30.0,kitchen,Strainer,credit card,success
84,85,15-12-2023,Sophia Robinson,80.0,book,The Hobbit,credit card,success
88,89,17-12-2023,Lucas Robinson,90.0,book,The Kite Runner,credit card,success
91,92,19-12-2023,Liam Turner,9.0,kitchen,Kitchen Tongs,credit card,success
92,93,19-12-2023,Noah Wilson,150.0,book,The Art of Happiness,credit card,success
95,96,21-12-2023,Oliver Brown,15.0,kitchen,Peeler,credit card,success
96,97,21-12-2023,Chloe Wilson,75.5,book,The Road,credit card,success
99,100,23-12-2023,Mia Robinson,10.0,kitchen,Can Opener,credit card,success